Repository ynput/ayon-houdini, pull requests merged in 2024-11, with the labels that each got.

#156 Fix textures not being collected and published along for `look` products
  client/ayon_houdini/plugins/publish/collect_usd_rop_layer_and_stage.py
Labels: type: bug

#153 Changing the order of BGEO cache format while creating
  client/ayon_houdini/plugins/create/create_bgeo.py
Labels: type: enhancement, community

#158 Fix Load Asset LOP and Load Shot LOP
  client/ayon_houdini/plugins/load/load_asset_lop.py
  client/ayon_houdini/plugins/load/load_shot_lop.py
Labels: type: bug

#159 Remove the :SDF_FORMAT_ARGS: from the collected filenames for Explicit Layer Save paths
  client/ayon_houdini/plugins/publish/collect_usd_layers.py
  client/ayon_houdini/plugins/publish/extract_usd.py
Labels: type: bug

#152 Do not enforce "Match Maya Mask" aperture expression on Load Camera (abc)
  client/ayon_houdini/plugins/load/load_camera.py
  server/settings/load.py
Labels: type: bug, sponsored

#161 Fix Load Asset LOP and Load Shot LOP (but better?)
  client/ayon_houdini/api/hda_utils.py
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/OnLoaded
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/PythonModule
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/OnLoaded
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/PythonModule
Labels: type: bug

#169 Allow `lopimportcam` for review
  client/ayon_houdini/plugins/publish/validate_scene_review.py
Labels: type: enhancement

#168 Render: Validate render product paths are unique between instances
  client/ayon_houdini/api/action.py
  client/ayon_houdini/plugins/publish/validate_render_product_paths_unique.py
Labels: type: enhancement, community

#166 Do not error on Load Warnings, but instead just log them.
  client/ayon_houdini/api/pipeline.py
Labels: type: enhancement

#148 Use `rop.opengl` family instead of `review`
  client/ayon_houdini/plugins/create/create_review.py
  client/ayon_houdini/plugins/publish/extract_rop.py
  client/ayon_houdini/plugins/publish/validate_review_colorspace.py
  client/ayon_houdini/plugins/publish/validate_scene_review.py
  package.py
Labels: type: enhancement, bump minor

#164 Bugfix: Farm cache publish support newer ayon-deadline versions
  client/ayon_houdini/plugins/publish/collect_cache_farm.py
Labels: type: bug

#175 174 cleanup pointcache and model families
  client/ayon_houdini/plugins/create/create_bgeo.py
  client/ayon_houdini/plugins/create/create_model.py
  client/ayon_houdini/plugins/create/create_pointcache.py
  client/ayon_houdini/plugins/publish/collect_instances_type.py
Labels: type: enhancement

#171 Remove `chunkSize` from houdini plugins
  client/ayon_houdini/plugins/create/create_arnold_rop.py
  client/ayon_houdini/plugins/create/create_karma_rop.py
  client/ayon_houdini/plugins/create/create_mantra_rop.py
  client/ayon_houdini/plugins/create/create_redshift_rop.py
  client/ayon_houdini/plugins/create/create_vray_rop.py
  client/ayon_houdini/plugins/publish/collect_arnold_rop.py
  client/ayon_houdini/plugins/publish/collect_chunk_size.py
  client/ayon_houdini/plugins/publish/collect_karma_rop.py
  client/ayon_houdini/plugins/publish/collect_mantra_rop.py
  client/ayon_houdini/plugins/publish/collect_redshift_rop.py
  client/ayon_houdini/plugins/publish/collect_vray_rop.py
Labels: type: enhancement

#167 Support new flipbook node for reviews
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/plugins/create/create_review.py
  client/ayon_houdini/plugins/publish/collect_review_data.py
  client/ayon_houdini/plugins/publish/extract_rop.py
  client/ayon_houdini/plugins/publish/validate_review_colorspace.py
  server/settings/create.py
Labels: type: enhancement, sponsored

#180 Support render targets for cache instances
  client/ayon_houdini/plugins/create/create_alembic_camera.py
  client/ayon_houdini/plugins/create/create_arnold_ass.py
  client/ayon_houdini/plugins/create/create_bgeo.py
  client/ayon_houdini/plugins/create/create_model.py
  client/ayon_houdini/plugins/create/create_pointcache.py
  client/ayon_houdini/plugins/create/create_redshift_proxy.py
  client/ayon_houdini/plugins/create/create_review.py
  client/ayon_houdini/plugins/create/create_staticmesh.py
  client/ayon_houdini/plugins/create/create_usd.py
  client/ayon_houdini/plugins/create/create_usd_look.py
  client/ayon_houdini/plugins/create/create_vbd_cache.py
  client/ayon_houdini/plugins/publish/collect_cache_farm.py
  client/ayon_houdini/plugins/publish/collect_farm_instances.py
  client/ayon_houdini/plugins/publish/extract_rop.py
Labels: type: enhancement, community
