Repository ynput/ayon-houdini, pull requests merged in 2024-09, with the labels that each got.

#81 Collect current file ignore the default untitled scene when no save or load has happened yet
  client/ayon_houdini/plugins/publish/collect_current_file.py
Labels: type: enhancement

#72 Support merged AOVs in arnold render
  client/ayon_houdini/plugins/publish/collect_arnold_rop.py
Labels: type: bug, sponsored

#82 Provide clearer error if no LOP path is set on USD render ROP
  client/ayon_houdini/plugins/publish/collect_local_render_instances.py
  client/ayon_houdini/plugins/publish/collect_render_colorspace.py
  client/ayon_houdini/plugins/publish/validate_render_products.py
Labels: type: enhancement

#93 Bugfix: local render remove redundant keys and add missing keys
  client/ayon_houdini/plugins/publish/collect_local_render_instances.py
Labels: type: bug, community

#94 Update "Use task handles" instance attribute label
  client/ayon_houdini/plugins/publish/collect_task_handles.py
Labels: type: maintenance

#74 Add support to run the workfile template builder on startup and simplify resolve houdini path
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/api/pipeline.py
  client/ayon_houdini/api/workfile_template_builder.py
Labels: type: enhancement, community

#96 Add settings for CreateUSDLook
  server/settings/create.py
Labels: type: enhancement

#67 Render layer name collector
  client/ayon_houdini/plugins/publish/collect_local_render_instances.py
  client/ayon_houdini/plugins/publish/collect_renderlayer.py
  package.py
Labels: type: enhancement

#80 USD ROP allow remapping explicit layer save paths to be remapped to AYON Entity URI
  client/ayon_houdini/plugins/publish/extract_usd.py
  server/settings/publish.py
Labels: type: enhancement

#107 Load filepath to node: Use <UDIM> token
  client/ayon_houdini/plugins/load/load_filepath.py
Labels: type: enhancement
