Repository ynput/ayon-houdini, pull requests merged in 2024-08, with the labels that each got.

#61 Set `force_valid_node_name` flag when creating placeholder nodes
  client/ayon_houdini/api/workfile_template_builder.py
Labels: type: bug

#62 fix wrong name when calling `setName`
  client/ayon_houdini/api/workfile_template_builder.py
Labels: type: bug

#59 Fix Collect USD Layers refactor and transfer `productGroup` to the extra product
  client/ayon_houdini/plugins/publish/collect_usd_layers.py
Labels: type: bug

#64 Add `ValidateWaitForRender`
  client/ayon_houdini/plugins/publish/validate_wait_for_render.py
Labels: type: bug, community

#75 Collect required data for local and farm render jobs to have a 'colorspace' value specified
  client/ayon_houdini/api/colorspace.py
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/plugins/publish/collect_arnold_rop.py
  client/ayon_houdini/plugins/publish/collect_karma_rop.py
  client/ayon_houdini/plugins/publish/collect_local_render_instances.py
  client/ayon_houdini/plugins/publish/collect_mantra_rop.py
  client/ayon_houdini/plugins/publish/collect_redshift_rop.py
  client/ayon_houdini/plugins/publish/collect_render_colorspace.py
  client/ayon_houdini/plugins/publish/collect_usd_render.py
  client/ayon_houdini/plugins/publish/collect_vray_rop.py
Labels: type: enhancement

#79 Fix USD OutputProcessor errors on USD export in Houdini 20.5+
  client/ayon_houdini/startup/husdplugins/outputprocessors/remap_to_publish.py
Labels: type: enhancement

#26 Load USD loaders with filepath from entity URI
  client/ayon_houdini/api/hda_utils.py
  client/ayon_houdini/api/plugin.py
  client/ayon_houdini/api/usd.py
  client/ayon_houdini/plugins/load/load_usd_layer.py
  client/ayon_houdini/plugins/load/load_usd_reference.py
  client/ayon_houdini/plugins/load/load_usd_sop.py
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/OnCreated
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/OnCreated
  server/settings/load.py
  server/settings/main.py
Labels: type: enhancement
