Repository ynput/ayon-houdini, pull requests merged in 2024-10, with the labels that each got.

#115 Define app host name
  package.py
Labels: type: maintenance

#124 Enable use selection by default on creators
  client/ayon_houdini/api/plugin.py
Labels: type: enhancement

#123 Add readme to otls directory
  client/ayon_houdini/startup/otls/README.md
Labels: documentation

#127 Create AYON Publish ROP PR refactor
  client/ayon_houdini/api/ayon_publish.py
  client/ayon_houdini/hooks/set_paths.py
  client/ayon_houdini/plugins/create/create_ayon_publish.py
  client/ayon_houdini/plugins/publish/collect_ayon_publish_outputs.py
  client/ayon_houdini/plugins/publish/collect_pub.py
  client/ayon_houdini/startup/otls/ayon_publish.hda/INDEX__SECTION
  client/ayon_houdini/startup/otls/ayon_publish.hda/Sections.list
  client/ayon_houdini/startup/otls/ayon_publish.hda/ynput_8_8dev_8_8Driver_1ayon__publish_8_81.7/AYON__icon.png
  client/ayon_houdini/startup/otls/ayon_publish.hda/ynput_8_8dev_8_8Driver_1ayon__publish_8_81.7/ExtraFileOptions
  client/ayon_houdini/startup/otls/ayon_publish.hda/ynput_8_8dev_8_8Driver_1ayon__publish_8_81.7/IconImage
  client/ayon_houdini/startup/otls/ayon_publish.hda/ynput_8_8dev_8_8Driver_1ayon__publish_8_81.7/Sections.list
Labels: type: maintenance

#125 Create Creator via TAB with null, keep null selected
  client/ayon_houdini/api/creator_node_shelves.py
Labels: type: enhancement

#145 Support Houdini context options from the ROP node for the USD collectors + validations
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/plugins/publish/collect_output_node.py
  client/ayon_houdini/plugins/publish/collect_render_products.py
  client/ayon_houdini/plugins/publish/collect_usd_look_assets.py
  client/ayon_houdini/plugins/publish/collect_usd_rop_layer_and_stage.py
  client/ayon_houdini/plugins/publish/validate_usd_look_assignments.py
  client/ayon_houdini/plugins/publish/validate_usd_look_contents.py
  client/ayon_houdini/plugins/publish/validate_usd_look_material_defs.py
  client/ayon_houdini/plugins/publish/validate_usd_render_arnold.py
  client/ayon_houdini/plugins/publish/validate_usd_rop_default_prim.py
  client/ayon_houdini/plugins/publish/validate_vdb_output_node.py
Labels: type: enhancement

#146 Group USD Explict Save Layer Products to "USD Layer" product group
  client/ayon_houdini/plugins/publish/collect_usd_layers.py
Labels: type: bug, sponsored

#139 Review: Don't add ftrack family
  client/ayon_houdini/plugins/publish/collect_review_data.py
Labels: type: enhancement

#126 Add a render resolution validator for USD Renders
  client/ayon_houdini/api/usd.py
  client/ayon_houdini/plugins/publish/validate_resolution.py
  server/settings/publish.py
Labels: type: enhancement

#150 Look: Validate material allow bindings from any purpose and configure in settings
  client/ayon_houdini/plugins/publish/validate_usd_look_assignments.py
  server/settings/publish.py
Labels: type: enhancement

#112 Load LOPs: Support update via context options (replace parm callbacks with expressions)
  client/ayon_houdini/api/hda_utils.py
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/INDEX__SECTION
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.createtimes
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.houdini_versions
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.modtimes
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/MessageNodes
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/OnLoaded
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/PythonModule
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/INDEX__SECTION
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.createtimes
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.houdini_versions
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.modtimes
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/OnLoaded
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/PythonModule
Labels: type: feature
