Repository ynput/ayon-houdini, pull requests merged in 2024-12, with the labels that each got.

#172 propagate the number of inputs of the subnetwork to the HDA and support publishing HDAs with spare parameters
  client/ayon_houdini/plugins/create/create_hda.py
  client/ayon_houdini/plugins/load/load_hda.py
  client/ayon_houdini/plugins/publish/extract_hda.py
Labels: type: enhancement, sponsored

#185 Containerise and parse container with `project_name` parm
  client/ayon_houdini/api/pipeline.py
Labels: type: enhancement

#163 Publish component builder LOP usd while maintaining hierarchical structure
  client/ayon_houdini/plugins/create/create_usd_componentbuilder.py
  client/ayon_houdini/plugins/publish/collect_componentbuilder_lop.py
  client/ayon_houdini/plugins/publish/collect_output_node.py
Labels: type: enhancement, sponsored

#196 Add version up workfile menu entry when enabled in core settings
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/startup/MainMenuCommon.xml
Labels: type: enhancement

#193 User friendly error messages
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/plugins/publish/collect_componentbuilder_lop.py
  client/ayon_houdini/plugins/publish/collect_output_node.py
  client/ayon_houdini/plugins/publish/collect_render_products.py
  client/ayon_houdini/plugins/publish/collect_usd_layers.py
  client/ayon_houdini/plugins/publish/extract_hda.py
  client/ayon_houdini/plugins/publish/extract_render.py
  client/ayon_houdini/plugins/publish/extract_rop.py
  client/ayon_houdini/plugins/publish/extract_usd.py
  client/ayon_houdini/plugins/publish/increment_current_file.py
  client/ayon_houdini/plugins/publish/save_scene.py
  client/ayon_houdini/plugins/publish/validate_abc_primitive_to_detail.py
  client/ayon_houdini/plugins/publish/validate_frame_token.py
  client/ayon_houdini/plugins/publish/validate_sop_output_node.py
Labels: type: enhancement

#120 Allow to set an explicit AOV identifier for USD render product using attribute `ayon:aov_identifier`
  client/ayon_houdini/plugins/publish/collect_render_products.py
Labels: type: enhancement, community
