Repository ynput/ayon-houdini, pull requests merged in 2025-04, with the labels that each got.

#244 Create USD: Do not lock `fileperframe` attribute
  client/ayon_houdini/plugins/create/create_usd.py
Labels: type: enhancement, community

#251 Create Review: Fix setting `imageFormat` extension on create
  client/ayon_houdini/plugins/create/create_review.py
Labels: type: bug, community

#245 Refactor Avalon and OpenPype terminology to `AYON`
  client/ayon_houdini/api/creator_node_shelves.py
  client/ayon_houdini/api/hda_utils.py
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/api/pipeline.py
  client/ayon_houdini/api/plugin.py
  client/ayon_houdini/api/shelves.py
  client/ayon_houdini/plugins/create/convert_legacy.py
  client/ayon_houdini/plugins/create/create_fbx.py
  client/ayon_houdini/plugins/create/create_karma_rop.py
  client/ayon_houdini/plugins/create/create_mantra_rop.py
  client/ayon_houdini/plugins/create/create_redshift_proxy.py
  client/ayon_houdini/plugins/create/create_redshift_rop.py
  client/ayon_houdini/plugins/create/create_usd.py
  client/ayon_houdini/plugins/create/create_vray_rop.py
  client/ayon_houdini/plugins/create/create_workfile.py
  client/ayon_houdini/plugins/load/load_fbx.py
  client/ayon_houdini/plugins/load/load_filepath.py
  client/ayon_houdini/plugins/load/load_hda.py
  client/ayon_houdini/plugins/load/load_image.py
  client/ayon_houdini/plugins/load/load_usd_layer.py
  client/ayon_houdini/plugins/load/load_usd_reference.py
  client/ayon_houdini/plugins/publish/collect_inputs.py
  client/ayon_houdini/plugins/publish/collect_usd_layers.py
  client/ayon_houdini/plugins/publish/validate_file_extension.py
  client/ayon_houdini/plugins/publish/validate_houdini_license_category.py
  client/ayon_houdini/plugins/publish/validate_product_name.py
  client/ayon_houdini/startup/otls/ayon.generic_loader.hda/ayon_8_8Lop_1generic__loader_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon.generic_loader.hda/ayon_8_8Object_1generic__loader_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon.generic_loader.hda/ayon_8_8Sop_1generic__loader_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/DialogScript
  server/__init__.py
  server/settings/__init__.py
  server/settings/conversion.py
  server/settings/publish.py
Labels: type: enhancement, community, bump minor

#252 Create Review: Fix `<USE_DISPLAY_NAME>` value in color correction create and review
  client/ayon_houdini/api/colorspace.py
  client/ayon_houdini/plugins/publish/validate_review_colorspace.py
Labels: type: bug, community

#257 use `variant` instance data not `product name`
  client/ayon_houdini/plugins/publish/collect_local_render_instances.py
Labels: type: bug
