Repository ynput/ayon-houdini, pull requests merged in 2025-02, with the labels that each got.

#215 Chore: Stricter ruff rules
  client/ayon_houdini/api/hda_utils.py
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/api/pipeline.py
  client/ayon_houdini/api/shelves.py
  client/ayon_houdini/api/workfile_template_builder.py
  client/ayon_houdini/plugins/create/create_alembic_camera.py
  client/ayon_houdini/plugins/create/create_arnold_rop.py
  client/ayon_houdini/plugins/create/create_hda.py
  client/ayon_houdini/plugins/create/create_karma_rop.py
  client/ayon_houdini/plugins/create/create_mantra_rop.py
  client/ayon_houdini/plugins/create/create_model.py
  client/ayon_houdini/plugins/create/create_pointcache.py
  client/ayon_houdini/plugins/create/create_redshift_rop.py
  client/ayon_houdini/plugins/create/create_review.py
  client/ayon_houdini/plugins/create/create_staticmesh.py
  client/ayon_houdini/plugins/create/create_usd.py
  client/ayon_houdini/plugins/create/create_usd_componentbuilder.py
  client/ayon_houdini/plugins/create/create_usd_look.py
  client/ayon_houdini/plugins/create/create_vray_rop.py
  client/ayon_houdini/plugins/load/load_filepath.py
  client/ayon_houdini/plugins/publish/collect_arnold_rop.py
  client/ayon_houdini/plugins/publish/collect_frames.py
  client/ayon_houdini/plugins/publish/collect_local_render_instances.py
  client/ayon_houdini/plugins/publish/collect_redshift_rop.py
  client/ayon_houdini/plugins/publish/collect_usd_rop_layer_and_stage.py
  client/ayon_houdini/plugins/publish/extract_active_view_thumbnail.py
  client/ayon_houdini/plugins/publish/extract_hda.py
  client/ayon_houdini/plugins/publish/extract_last_published.py
  client/ayon_houdini/plugins/publish/extract_render.py
  client/ayon_houdini/plugins/publish/extract_rop.py
  client/ayon_houdini/plugins/publish/extract_usd.py
  client/ayon_houdini/plugins/publish/save_scene.py
  client/ayon_houdini/plugins/publish/validate_frame_range_frames_to_fix.py
  client/ayon_houdini/plugins/publish/validate_render_product_paths_unique.py
  client/ayon_houdini/plugins/publish/validate_resolution.py
  client/ayon_houdini/plugins/publish/validate_review_colorspace.py
  client/ayon_houdini/plugins/publish/validate_sop_output_node.py
  client/ayon_houdini/plugins/publish/validate_usd_asset_contribution_default_prim.py
  client/ayon_houdini/plugins/publish/validate_usd_output_node.py
  client/ayon_houdini/plugins/publish/validate_wait_for_render.py
  client/ayon_houdini/plugins/workfile_build/create_placeholder.py
  client/ayon_houdini/plugins/workfile_build/load_placeholder.py
  ruff.toml
Labels: type: enhancement

#213 Fix Load Filepath legacy update
  client/ayon_houdini/api/hda_utils.py
Labels: type: bug

#216 Create Workfile: Use cached entity queries from CreateContext
  client/ayon_houdini/plugins/create/create_workfile.py
Labels: type: enhancement

#217 Chore: Remove 'six' usage
  client/ayon_houdini/api/lib.py
  client/ayon_houdini/api/plugin.py
Labels: type: enhancement

#223 expand string before returning path in generic loaders
  client/ayon_houdini/api/hda_utils.py
Labels: type: bug

#144 Allow creating more product types as USD with USD contribution workflow and better defaults.
  client/ayon_houdini/plugins/create/create_usd.py
  client/ayon_houdini/plugins/create/create_usd_look.py
  client/ayon_houdini/plugins/publish/collect_task_handles.py
  client/ayon_houdini/plugins/publish/validate_sop_output_node.py
Labels: type: enhancement

#226 fix parameters names of lop import and load shot
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/INDEX__SECTION
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/.OPdummydefs
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.createtimes
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.modtimes
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/INDEX__SECTION
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/.OPdummydefs
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.createtimes
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.modtimes
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/DialogScript
Labels: type: bug

#232 Remove deprecated settings
  server/settings/publish.py
Labels: type: maintenance

#233 Load Asset/Shot LOP: revert parm name change except for the fixed `folder_name`
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_import.hda/ayon_8_8Lop_1lop__import_8_81.0/DialogScript
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/Contents.dir/Contents.mime
  client/ayon_houdini/startup/otls/ayon_lop_load_shot.hda/ayon_8_8Lop_1load__shot_8_81.0/DialogScript
Labels: type: bug
