Repository ynput/ayon-houdini, pull requests merged in 2025-07, with the labels that each got.

#281 Templated Workfile Build: make `fill_data` argument optional in `resolve_template_path`
  client/ayon_houdini/api/workfile_template_builder.py
Labels: type: bug

#284 Adapt to opmenu hierarchy of houdini `20.5`
  client/ayon_houdini/startup/OPmenu.xml
Labels: type: bug

#290 Add Creator descriptions
  client/ayon_houdini/plugins/create/create_alembic_camera.py
  client/ayon_houdini/plugins/create/create_arnold_ass.py
  client/ayon_houdini/plugins/create/create_arnold_rop.py
  client/ayon_houdini/plugins/create/create_bgeo.py
  client/ayon_houdini/plugins/create/create_copernicus.py
  client/ayon_houdini/plugins/create/create_fbx.py
  client/ayon_houdini/plugins/create/create_hda.py
  client/ayon_houdini/plugins/create/create_karma_rop.py
  client/ayon_houdini/plugins/create/create_mantra_rop.py
  client/ayon_houdini/plugins/create/create_model.py
  client/ayon_houdini/plugins/create/create_pointcache.py
  client/ayon_houdini/plugins/create/create_redshift_proxy.py
  client/ayon_houdini/plugins/create/create_redshift_rop.py
  client/ayon_houdini/plugins/create/create_review.py
  client/ayon_houdini/plugins/create/create_usd.py
  client/ayon_houdini/plugins/create/create_vbd_cache.py
  client/ayon_houdini/plugins/create/create_vray_rop.py
Labels: type: enhancement, community

#279 Publish: Use new workfiles API to increment current workfile.
  client/ayon_houdini/plugins/publish/increment_current_file.py
  client/ayon_houdini/startup/MainMenuCommon.xml
Labels: type: enhancement, sponsored
