Repository ynput/ayon-houdini, pull requests merged in 2025-03, with the labels that each got.

#238 Add "rig" product type to publish APEX rigs to BGEO
  client/ayon_houdini/plugins/create/create_rig.py
  client/ayon_houdini/plugins/publish/collect_frames.py
  client/ayon_houdini/plugins/publish/collect_task_handles.py
Labels: type: enhancement

#240 Create Redshift ROP: Expose `multi_layered_mode` to settings
  client/ayon_houdini/plugins/create/create_redshift_rop.py
  server/settings/create.py
Labels: type: enhancement, sponsored

#234 Add Create Model (FBX) creator to create FBX with model product type
  client/ayon_houdini/plugins/create/create_fbx.py
  server/settings/create.py
Labels: community

#212 Collapse loaded paths to AYON project root env vars
  client/ayon_houdini/api/plugin.py
  client/ayon_houdini/plugins/load/load_alembic.py
  client/ayon_houdini/plugins/load/load_alembic_archive.py
  client/ayon_houdini/plugins/load/load_ass.py
  client/ayon_houdini/plugins/load/load_bgeo.py
  client/ayon_houdini/plugins/load/load_camera.py
  client/ayon_houdini/plugins/load/load_fbx.py
  client/ayon_houdini/plugins/load/load_image.py
  client/ayon_houdini/plugins/load/load_redshift_proxy.py
  client/ayon_houdini/plugins/load/load_usd_layer.py
  client/ayon_houdini/plugins/load/load_usd_reference.py
  client/ayon_houdini/plugins/load/load_usd_sop.py
  client/ayon_houdini/plugins/load/load_vdb.py
  server/settings/load.py
Labels: type: enhancement, sponsored

#243 Support Houdini-native `context_options` arguments to `LopNode` methods
  client/ayon_houdini/plugins/publish/collect_usd_rop_layer_and_stage.py
Labels: type: enhancement, community

#246 Manage: Add "Select in scene" inventory action
  client/ayon_houdini/plugins/inventory/select_containers.py
Labels: type: enhancement, community

#248 Validate USD Look Disallowed Types: make customizable in settings
  client/ayon_houdini/plugins/publish/validate_usd_look_disallowed_types.py
  server/settings/publish.py
Labels: type: enhancement, community

#247 Manage: Add "Show parameters" action
  client/ayon_houdini/plugins/inventory/show_parameters.py
Labels: type: enhancement, community

#250 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature
